更新脚本，添加客户端部分，方便 Linux 环境使用
Signed-off-by: Tao Wang <twang2218@gmail.com>

diff --git a/bin/ss b/bin/ss
--- a/bin/ss
+++ b/bin/ss
@@ -3,13 +3,22 @@
 #
 # 短连接地址：http://t.cn/RWiJf2w
 #
-# set -e
+# 将该脚本放入 `~/bin/` 目录下，打通路径并赋予可执行权限后即可使用。
 #
-# * 启动:   ./ss start
-# * 停止:   ./ss stop
-# * 状态:  ./ss status
+#   $ curl http://t.cn/RWiJf2w -o ~/bin/ss
+#   $ chmod a+x ~/bin/ss
+#
+# 使用命令：
+#
+# * 启动代理:   ss proxy start
+# * 停止代理:   ss proxy stop
+# * 代理状态:   ss status
 # * 给命令行加载代理环境变量: eval $(./ss env)
 # * 卸载命令行的代理环境变量: eval $(./ss env --unset)
+# * 配置 DNS:   ss dns start
+# * 删除 DNS:   ss dns stop
+# * 配置本地 hosts 文件：  ss host start
+# * 删除本地 hosts 文件：  ss host stop
 #
 # 使用该脚本的前提条件
 #
@@ -31,22 +40,56 @@
 
 DOMAIN=lab99.org
 NAME=ss
-PORT=443
+SERVER_PORT=443
+LOCAL_PORT=1080
 MODE=aes-256-gcm
 TOKEN=dockerrocks
 
-function create_machine() {
-  local name=$1
+# Vultr Region ID
+# * 25 - Tokyo, JP
+# * 19 - Sydney, AU
+# * 40 - Singapore
+# * 39 - Miami
+VULTR_REGION=39
+
+# Vultr Plan ID
+# * 201 - 1024 MB RAM,25 GB SSD,1.00 TB BW - $5/month
+# * 202 - 2048 MB RAM,40 GB SSD,2.00 TB BW - $10/month
+VULTR_PLAN=201
+
+function provision_linux() {
+  # Install Docker Machine
+  curl -fL https://github.com/docker/machine/releases/download/v0.14.0/docker-machine-`uname -s`-`uname -m` -o /tmp/docker-machine
+  sudo install /tmp/docker-machine /usr/local/bin/docker-machine
+  # Install Docker Machine Vultr Driver
+  curl -fL https://github.com/janeczku/docker-machine-vultr/releases/download/v1.3.0/docker-machine-driver-vultr-`uname -s`-`uname -m` -o /tmp/docker-machine-driver-vultr
+  sudo install /tmp/docker-machine-driver-vultr /usr/local/bin/docker-machine-driver-vultr
+}
+
+function provision_mac() {
+  brew install docker-machine docker-machine-driver-vultr docker-machine-driver-digitalocean
+}
+
+function provision() {
+  local subcmd=$1
   shift
+  case "$subcmd" in
+    linux)    provision_linux ;;
+    mac)      provision_mac ;;
+    *)        echo "Usage: $0 provision <linux|mac>" ;;
+  esac
+}
+
+function create_machine() {
   # Create a docker host
-  docker-machine create -d vultr --vultr-region-id=25 $name
-  docker-machine ls | grep $name
+  docker-machine create -d vultr $NAME
+  docker-machine ls | grep $NAME
 
   # Prepare the machine
-  docker-machine ssh $name  << EOF
+  docker-machine ssh $NAME  << EOF
   apt-get update
   apt-get install --install-recommends -y linux-generic-hwe-16.04 
-  apt-get dist-upgrade -y
+  # apt-get dist-upgrade -y
   echo 'net.core.default_qdisc=fq' >> /etc/sysctl.conf
   echo 'net.ipv4.tcp_congestion_control=bbr' >> /etc/sysctl.conf
   reboot
@@ -54,116 +97,161 @@ EOF
 
   sleep 20
 
-  docker-machine ssh $name "sysctl net.ipv4.tcp_available_congestion_control; lsmod | grep bbr"
+  docker-machine ssh $NAME "sysctl net.ipv4.tcp_available_congestion_control; lsmod | grep bbr"
 }
 
 function remove_machine() {
-  local name=$1
   # Simply remove the machine
-  docker-machine rm -y $name
-  echo "Removed docker host: $name"
+  docker-machine rm -y $NAME
+  echo "Removed docker host: $NAME"
+}
+
+function get_machine_ip() {
+  ip=$(docker-machine ip $NAME)
+  if [ -z "$ip" ]; then
+    echo "Cannot found docker-machine: $NAME"
+    exit 1
+  fi
+
+  echo $ip
 }
 
 function create_dns_record() {
-  local name=$1
-  local domain=$2
-
   # Get IP of the docker host
-  ip=$(docker-machine ip $name)
-  if [ -z "$ip" ]; then
-    echo "Cannot found docker-machine: $name"
-    return 1
-  fi
+  local ip=$(get_machine_ip)
 
   # Create DNS record for constant usage
-  local id=`doctl compute domain records list $domain | grep $name | cut -d' ' -f1`
+  local id=`doctl compute domain records list $DOMAIN | grep $NAME | cut -d' ' -f1`
   if [ -z "$id" ]; then
     # create one
-    id=`doctl compute domain records create $domain --record-name=$name --record-data=$ip --record-type=A | grep $name | cut -d' ' -f1`
+    id=`doctl compute domain records create $DOMAIN --record-name=$NAME --record-data=$ip --record-type=A | grep $NAME | cut -d' ' -f1`
     if [ -z "$id" ]; then
-      echo "Failed to create the $name.$domain records"
+      echo "Failed to create the $NAME.$DOMAIN records"
     else
-      echo "Created DNS record: $name.$domain => $ip"
+      echo "Created DNS record: $NAME.$DOMAIN => $ip"
     fi
   else
     # update the existing one
-    doctl compute domain records update $domain --record-id=$id --record-data=$ip
-    echo "Updated DNS record: $name.$domain => $ip"
+    doctl compute domain records update $DOMAIN --record-id=$id --record-data=$ip
+    echo "Updated DNS record: $NAME.$DOMAIN => $ip"
   fi
 }
 
 function remove_dns_record() {
-  local name=$1
-  local domain=$2
-
   # Remove the dns record
-  local id=`doctl compute domain records list $domain | grep $name | cut -d' ' -f1`
+  local id=`doctl compute domain records list $DOMAIN | grep $NAME | cut -d' ' -f1`
   if [ -z "$id" ]; then
-    echo "DNS record '$name.$domain' does not exist"
+    echo "DNS record '$NAME.$DOMAIN' does not exist"
   else
     doctl compute domain records delete lab99.org "$id" -f
-    echo "DNS record '$name.$domain' removed"
+    echo "DNS record '$NAME.$DOMAIN' removed"
   fi
 }
 
 function create_hosts_record() {
-  local name=$1
-  local domain=$2
-
   # Get IP of the docker host
-  ip=$(docker-machine ip $name)
-  if [ -z "$ip" ]; then
-    echo "Cannot found docker-machine: $name"
-    return 1
-  fi
+  local ip=$(get_machine_ip)
 
   # Remove the host record if it exists
-  remove_hosts_record $name $domain
+  remove_hosts_record
 
   # Append record to /etc/hosts
-  echo "$ip   $name.$domain" | sudo tee -a /etc/hosts
+  echo "$ip   $NAME.$DOMAIN" | sudo tee -a /etc/hosts
 }
 
 function remove_hosts_record() {
-  local name=$1
-  local domain=$2
-
-  if grep -q $name.$domain /etc/hosts; then
-    sudo sed -i "/$name.$domain/d" /etc/hosts
+  if grep -q $NAME.$DOMAIN /etc/hosts; then
+    sudo sed -i "/$NAME.$DOMAIN/d" /etc/hosts
   fi
 }
 
-function start_proxy() {
-  local name=$1
-  local port=$2
-  local mode=$3
-  local token=$4
-
-  # Start Proxy
-  eval $(docker-machine env $name)
-  docker run --name $name -d -p $port:$port\
+function start_server() {
+  # Start Proxy on remote server
+  eval $(docker-machine env $NAME)
+  # Stop the running container
+  docker rm -f $NAME
+  # Start a new one
+  docker run --name $NAME -d \
+    -p $SERVER_PORT:$SERVER_PORT \
+    -p $SERVER_PORT:$SERVER_PORT/udp \
     mritd/shadowsocks \
-      -s "-s 0.0.0.0 -p $port -m $mode -k $token --fast-open" 
+      -m "ss-server" \
+      -s "-s 0.0.0.0 -p $SERVER_PORT -m $MODE -k $TOKEN --fast-open" \
+      -x -e "kcpserver" \
+      -k "-t 127.0.0.1:$SERVER_PORT -l :$SERVER_PORT -mode fast2"
 }
 
-function start() {
-  create_machine $NAME
-  # create_dns_record $NAME $DOMAIN
-  create_hosts_record $NAME $DOMAIN
-  start_proxy $NAME $PORT $MODE $TOKEN
+function start_client() {
+  # Run client on the local
+  eval $(docker-machine env --unset)
+  # Stop the running container
+  docker rm -f $NAME
+  # Start a new one
+  local ip=$(get_machine_ip)
+  docker run --name $NAME -dt -p $LOCAL_PORT:$LOCAL_PORT \
+    mritd/shadowsocks \
+      -m "ss-local" \
+      -s "-s 127.0.0.1 -p $SERVER_PORT -b 0.0.0.0 -l $LOCAL_PORT -m $MODE -k $TOKEN --fast-open" \
+      -x -e "kcpclient" \
+      -k "-r ${ip}:$SERVER_PORT -l :$SERVER_PORT -mode fast2"
 }
 
-function stop() {
-  remove_machine $NAME
-  # remove_dns_record $NAME $DOMAIN
-  remove_hosts_record $NAME $DOMAIN
+function stop_client() {
+  # Stop client on the local
+  eval $(docker-machine env --unset)
+  docker stop $NAME
+  docker rm -f $NAME
+}
+
+function start_proxy() {
+  eval $(environment --unset)
+  create_machine
+  start_server
+  start_client
+}
+
+function stop_proxy() {
+  eval $(environment --unset)
+  stop_client
+  remove_machine
 }
 
 function status() {
+  eval $(environment --unset)
   docker-machine ls --filter "name=$NAME"
   eval $(docker-machine env $NAME)
   docker ps -f "name=$NAME" -a
   docker logs $@ $NAME
+}
+
+function proxy() {
+  local subcmd=$1
+  shift
+  case "$subcmd" in
+    start)  start_proxy $@ ;;
+    stop)   stop_proxy $@ ;;
+    *)      echo "Usage: $0 proxy <start|stop>" ;;
+  esac
+}
+
+function dns() {
+  local subcmd=$1
+  shift
+  case "$subcmd" in
+    start)    create_dns_record ;;
+    stop)     remove_dns_record ;;
+    *)        echo "Usage: $0 dns <start|stop>" ;;
+  esac
+}
+
+function host() {
+  local subcmd=$1
+  shift
+  case "$subcmd" in
+    start)    create_host_record ;;
+    stop)     remove_host_record ;;
+    *)        echo "Usage: $0 host <start|stop>" ;;
+  esac
 }
 
 function environment() {
@@ -177,8 +265,8 @@ function environment() {
     echo "# Run: eval \$($0 env --unset)"
   else
     # Set proxy env
-    http_proxy=socks5h://127.0.0.1:1086
-    echo export http_proxy=socks5h://127.0.0.1:1086
+    local http_proxy=socks5://127.0.0.1:$LOCAL_PORT
+    echo export http_proxy=$http_proxy
     echo export https_proxy=$http_proxy
     echo export HTTP_PROXY=$http_proxy
     echo export HTTPS_PROXY=$http_proxy
@@ -191,9 +279,11 @@ command=$1
 shift
 
 case $command in
-  start)   start ;;
-  stop)    stop ;;
-  status)  status ;;
-  env)     environment $@ ;;
-  *)       echo "Usage: $0 (start|stop|status|env)" ;;
+  provision)    provision $@ ;;
+  proxy)        proxy $@ ;;
+  dns)          dns $@ ;;
+  host)         host $@ ;;
+  status)       status ;;
+  env)          environment $@ ;;
+  *)            echo "Usage: $0 (proxy|dns|host|status|env|provision)" ;;
 esac
